{
 "title": "Khulnasoft / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(khulnasoft_ws_manager_mk2_workspace_phase_total, cluster)"
    }
   },
   { "name": "cell", "label": "Cell", "query": { "query": "label_values(cell)" } }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Khulnasoft Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(khulnasoft_version_info{cell=\"$cell\"}) by (khulnasoft_version)"
    }
   ]
  },
  {
   "title": "Stats(7d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sum(khulnasoft_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "min_over_time(sum(khulnasoft_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Min"
    },
    {
     "expr": "max_over_time(sum(khulnasoft_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"})[7d:10m])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Workspaces by phase",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(khulnasoft_ws_manager_mk2_workspace_phase_total{cell=\"$cell\"}) by (phase)",
     "legendFormat": "{{ label_name }}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(khulnasoft_ws_manager_mk2_workspace_phase_total{phase=\"Running\",cell=\"$cell\"}) by (cluster,type)",
     "legendFormat": "{{cluster}}: {{type}}"
    }
   ]
  },
  {
   "title": "Khulnasoft Version",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(khulnasoft_version_info{cell=\"$cell\"}) by (khulnasoft_version)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Running workspaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Running Workspaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(khulnasoft_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\", phase=\"Running\", cell=\"$cell\"}) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(khulnasoft_ws_manager_mk2_workspace_activity_total{cluster=~\"$cluster\",cell=\"$cell\",active=\"false\"})",
     "legendFormat": "Regular Not Active"
    }
   ]
  },
  { "title": "SSH Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Active SSH Connections",
   "type": "timeseries",
   "description": "The # of connections over SSH. It's possible for a single workspace to have many SSH connections. For example, two tabs on my local machine could both be connected to the same workspace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(cluster) (khulnasoft_ws_proxy_ssh_connection_count{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "IPFS Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "IPFS Storage Remaining",
   "type": "timeseries",
   "description": "Amount of available storage remaining for IPFS in the workspace clusters. This storage is used as workspace image cache. Clusters must get recreated before this gets too low.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{device=\"/dev/mapper/lvm--disk-ipfs\", node=~\"services-.*\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workspace node's normalized Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace node's normalized load average",
   "type": "graph",
   "description": "Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(nodepool:node_load1:normalized{cluster=~\"$cluster\", nodepool=~\".*workspace.*\",cell=\"$cell\"}) by (node))\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "1\n", "legendFormat": "Node Max Load Avg" }
   ]
  },
  {
   "title": "Headless node's normalized Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Headless node's normalized load average",
   "type": "graph",
   "description": "Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(nodepool:node_load1:normalized{cluster=~\"$cluster\", nodepool=~\".*headless.*\",cell=\"$cell\"}) by (node))\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "1\n", "legendFormat": "Node Max Load Avg" }
   ]
  },
  {
   "title": "Workspace Startup time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Regular Workspace Startup time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(rate(khulnasoft_ws_manager_mk2_workspace_startup_seconds_bucket{cluster=~\"$cluster\",type=\"Regular\",cell=\"$cell\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workspace Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Phases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (type, phase)(khulnasoft_ws_manager_mk2_workspace_phase_total{cluster=~\"$cluster\",cell=\"$cell\",phase!=\"Running\"})",
     "legendFormat": "{{type}} - {{phase}}"
    }
   ]
  },
  {
   "title": "Workspace failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace Failures per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(khulnasoft_ws_manager_mk2_workspace_stops_total{cluster=~\"$cluster\",cell=\"$cell\",reason=\"failed\"}[5m])\n) by (cluster, type) OR on() vector(0)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{cluster=~\"$cluster\",cell=\"$cell\"}) by (nodepool)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  }
 ]
}