/**
 * Copyright (c) 2025 Khulnasoft GmbH. All rights reserved.
 * Licensed under the GNU Affero General Public License (AGPL).
 * See License.AGPL.txt in the project root for license information.
 */

// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file khulnasoft/v1/auditlogs.proto (package khulnasoft.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListAuditLogsRequest, ListAuditLogsResponse } from "./auditlogs_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service khulnasoft.v1.AuditLogService
 */
export const AuditLogService = {
  typeName: "khulnasoft.v1.AuditLogService",
  methods: {
    /**
     * ListAuditLogs returns a list of audit logs
     *
     * @generated from rpc khulnasoft.v1.AuditLogService.ListAuditLogs
     */
    listAuditLogs: {
      name: "ListAuditLogs",
      I: ListAuditLogsRequest,
      O: ListAuditLogsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
