{
 "title": "Meta Services",
 "tags": [ "khulnasoft-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"redis\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\", node=~\".*-services-.*\"}, node)"
    }
   },
   {
    "name": "component",
    "label": "component",
    "query": "content-service, dashboard, db, proxy, server, ws-manager-bridge, image-builder, image-builder-mk3"
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster: CPU per Pod (# of vCores)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$component-.*\"}[5m])\n) by (pod, cluster, node)",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "$cluster: RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$component-.*\"}) by (pod, cluster, node)",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "$cluster: Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$component-.*\"}[5m])\n) by (pod, cluster, node)",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  }
 ]
}