{
 "title": "Network limiting",
 "description": "Shows statistics about network limiting",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(khulnasoft_ws_daemon_netlimit_connections_dropped_bytes,node)"
    }
   },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": {
     "query": "label_values(khulnasoft_ws_daemon_netlimit_connections_dropped_bytes{node=\"$node\"},workspace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(khulnasoft_ws_daemon_netlimit_connections_dropped_packets{node=~\"$node\", workspace=~\"$workspace\"}) by(node, workspace)",
     "legendFormat": "{{workspace}}"
    }
   ]
  },
  {
   "title": "Dropped bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(khulnasoft_ws_daemon_netlimit_connections_dropped_bytes{node=~\"$node\", workspace=~\"$workspace\"}) by (node, workspace)",
     "legendFormat": "{{workspace}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(khulnasoft_ws_daemon_netlimit_connections_dropped_packets[1m])) by(workspace) != 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}