packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go:lib
      - components/khulnasoft-db:latest-migration
    prep:
      - ["sh", "-c", "mkdir -p cmd/resources"]
      - ["sh", "-c", "cat _deps/components-khulnasoft-db--latest-migration/latest-migration.txt > cmd/resources/latest-migration.txt"]
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/khulnasoft-com/khulnasoft/service-waiter/cmd.Version=commit-${__git_commit}'"]
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: blazedock.Dockerfile
      metadata:
        helm-component: serviceWaiter
      image:
        - ${imageRepoBase}/service-waiter:${version}
        - ${imageRepoBase}/service-waiter:commit-${__git_commit}
