{
 "title": "Cardinality Management - Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(metrics_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "💡Tips for metrics",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "## Individual metrics with a high number of series associated with them:\n\n* Could you drop some labels on that metric to reduce its cardinality?\n\n* Could you drop the entire metric?\n\n* Could you replace the large number of unique label/label value pairs?"
   }
  },
  {
   "title": "Total Metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total timeseries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metric:timeseries_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💡Tips for labels",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "## Labels with a high number of unique values:\n\n* Could you drop this label entirely?\n\n* Could you decrease the number of unique values for it?\n\n* If you still need this information in this label, could you instead store it in a log file?"
   }
  },
  {
   "title": "Top 15 - High cardinality metrics",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n      sum(metric:timeseries_total{cluster=~\"$cluster\"}) by (metric)\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n        sum(metric:timeseries_total{cluster=~\"$cluster\"}) by (metric) / sum(metric:timeseries_total{cluster=~\"$cluster\"})\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 15 labels by unique value count",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n        sum(cardinality_exporter_label_value_count_by_label_name{cluster=~\"$cluster\"}) by (label)\r\n    )\r\n)",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n        sum(cardinality_exporter_label_value_count_by_label_name{cluster=~\"$cluster\"}) by (label) \r\n        / \r\n        sum(cardinality_exporter_label_value_count_by_label_name{cluster=~\"$cluster\"})\r\n    )\r\n)",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sort_desc(\r\n    topk(15, \r\n        sum(cardinality_exporter_memory_by_label_bytes{cluster=~\"$cluster\"}) by (label)\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}