{
 "title": "Observability",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus (Satellite)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Containers Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{cluster=~\"$cluster\", pod=\"prometheus-k8s-0\", container=\"prometheus\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Prometheus Container Restarts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=\"prometheus-k8s-0\", container=\"prometheus\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Prometheus Memory Remaining (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((kube_pod_container_resource_limits{container=\"prometheus\", resource=\"memory\", cluster=~\"$cluster\"}) - on(cluster) avg by (cluster) (container_memory_working_set_bytes{container=\"prometheus\", cluster=~\"$cluster\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Free CPUs (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{container=\"prometheus\", resource=\"cpu\", cluster=~\"$cluster\"} - on (cluster) sum  by (cluster) (rate(container_cpu_usage_seconds_total{container=\"prometheus\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Victoria Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Prometheus Containers Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod=\"victoriametrics-0\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "VM Container Restarts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=\"victoriametrics-0\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "VM Memory Remaining (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"victoriametrics\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"victoriametrics\", resource=\"memory\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "VM Free CPUs (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container=\"victoriametrics\"}[1m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"victoriametrics\", resource=\"cpu\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "VM Remaining Storage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"prod-monitoring-central\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"monitoring-central\", persistentvolumeclaim=\"storage-volume-victoriametrics-0\"})))",
     "legendFormat": "Available storage"
    }
   ]
  },
  { "title": "Alertmanager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Alertmanager Containers Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\"alertmanager-slo-0\", container=\"alertmanager\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Alertmanager Container Restarts",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=\"alertmanager-slo-0\", container=\"alertmanager\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Alertmanager Memory Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"alertmanager-slo-0\", container=\"alertmanager\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=\"alertmanager-slo-0\", container=\"alertmanager\", resource=\"memory\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Alertmanager CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod=\"alertmanager-slo-0\", container=\"alertmanager\"}[1m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=\"alertmanager-slo-0\", container=\"alertmanager\", resource=\"cpu\"}",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}