{
 "title": "Preview Environments",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kubevirt_info, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\"},  kubernetes_vmi_label_kubevirt_io_nodeName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Previews",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Previews per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$node: Running Previews",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_vmi_memory_used_total_bytes{cluster=~\"$cluster\", kubernetes_vmi_label_kubevirt_io_nodeName=\"$node\"})"
    }
   ]
  },
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Preview Start SLO",
   "type": "text",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 17 },
   "options": {
    "content": "We have an SLO for preview starts in Honeycomb. You can see the SLO [here](https://ui.honeycomb.io/khulnasoft/datasets/werft/slo/zRm48xoKMXf/Preview-Start). Alternatively you can use [this query](https://ui.honeycomb.io/khulnasoft/datasets/werft/result/a64cNk4sArf) to dig into succesful and failed SLI events. The definition of the SLO can be found [here](https://www.notion.so/khulnasoft/Preview-Environment-Service-Level-Indicators-SLIs-55b649ad17774f279c142af55ad2fec7#f483f73aa4974ad3b8b6825fa2f251fa)."
   }
  },
  {
   "title": "Preview environments should be able to communicate to the internet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\r\n  sum(rate(http_prober_probes_failed_total{environment=\"preview-environments\"}[5m]))\r\n  /\r\n  sum(rate(http_prober_probe_duration_seconds_count{environment=\"preview-environments\"}[5m]))\r\n)",
     "legendFormat": "Probe success ratio"
    }
   ]
  },
  {
   "title": "K3s running in preview environments should respond successfully to Read/Write requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"2..|4..\", host=~\"127.0.0.1.*\", environment=\"preview-environments\"}[5m]))\r\n/ \r\nsum(rate(rest_client_requests_total{host=~\"127.0.0.1.*\", environment=\"preview-environments\"}[5m]))",
     "legendFormat": "K3s requests success rate"
    }
   ]
  }
 ]
}